### PR TITLE
Fix endianess for bigendian archs

### LINKED ISSUE #176: Different endianness support
sparrow seems to make incorrect assumption on endianness, see `build.log` in https://koji.fedoraproject.org/koji/taskinfo?taskID=121660164

### PR DESCRIPTION
**Pull request by Alex-PLACET**
Fix #176

### CODE REVIEW

File: test/test_arrow_array.cpp [hunk 1]
```diff
@@ -57,7 +57,8 @@ void check_common(
         CHECK_EQ(array->children[i], children_ptr[i]);
     }
     CHECK_EQ(array->dictionary, dictionary_pointer);
-    CHECK_EQ(array->release, sparrow::release_arrow_array);
+    const bool is_release_arrow_array = array->release == &sparrow::release_arrow_array;
+    CHECK(is_release_arrow_array);
```
Comment (Alex-PLACET) [inline test/test_arrow_array.cpp:61]: Fix a fpermissive issue

**Comment by SylvainCorlay** [comment]
#165 is merged. This can be rebased.

**Review by JohanMabille — APPROVED** [review]
